### ISSUE TITLE
Should the JobName move of Parameters

### ISSUE THREAD

**Issue by adam-fowler** [hummingbird-project/swift-jobs#16]
I was asking if the interface could change were the we pass the name of the job at the time of registration instead.

```swift
queue.registerJob(
            parameters: AnotherParameters.self,
            jobName: "SomeJobName"
            maxRetryCount: 4)
        { (parameters: AnotherParameters, _) in
        }
```

_Originally posted by @thoven87 in https://github.com/hummingbird-project/swift-jobs/pull/14#discussion_r1729013979_

**Comment by adam-fowler** [comment]
We need to ensure that the correct parameter type is sent to a job. If I setup a job as follows
```swift
queue.registerJob(
            parameters: Parameters.self,
            jobName: "SomeJobName"
            maxRetryCount: 4)
        { parameters, _ in
        }
```
I want to ensure you can't do the following ie make a job request with a different parameter structure 
```swift
struct DifferentParameters {
    ... something different from Parameters
}
let parameters = DifferentParameters()
queue.push(jobName: "SomeJobName", parameters: parameters)
```
If you were allowed to do that you would be polluting the job queue with invalid data which would not decode correctly. 

So I need to associate the name with the correct parameter type. You don't need to use the `JobParameters` type to do this though. It is used to centralize this in one type, But you have other options

You can create a JobDefinition (this type is used internally to store jobs)
```swift
let job = JobDefinition(id: "testBasic") { (parameters: MyParameters, context) in
    // do job
}
jobQueue.registerJob(job)
jobQueue.push(job.id, myParameters)
```

or

You can break it down into its constituent parts.
```swift
extension JobIdentifier where Parameters == Int {
    static var test: Self { .init("test") }
}
jobQueue.registerJob(id: .test) { _, _ in
    // do job
}
jobQueue.push(.test, 5)
```

This along with the `JobDefinition` allow you to use any type as parameters but these methods also have their own issues as well. The `JobDefinition` requires you to store the id as a variable somewhere. Splitting up the Job definition into parameters, id, and closure means it spread across multiple places in your code which could get messy.

**Comment by thoven87** [comment]
> We need to ensure that the correct parameter type is sent to a job. If I setup a job as follows
> 
> ```swift
> queue.registerJob(
>             parameters: Parameters.self,
>             jobName: "SomeJobName"
>             maxRetryCount: 4)
>         { parameters, _ in
>         }
> ```
> 
> I want to ensure you can't do the following ie make a job request with a different parameter structure
> 
> ```swift
> struct DifferentParameters {
>     ... something different from Parameters
> }
> let parameters = DifferentParameters()
> queue.push(jobName: "SomeJobName", parameters: parameters)
> ```
> 
> If you were allowed to do that you would be polluting the job queue with invalid data which would not decode correctly.
> 
> So I need to associate the name with the correct parameter type. You don't need to use the `JobParameters` type to do this though. It is used to centralize this in one type, But you have other options
> 
> You can create a JobDefinition (this type is used internally to store jobs)
> 
> ```swift
> let job = JobDefinition(id: "testBasic") { (parameters: MyParameters, context) in
>     // do job
> }
> jobQueue.registerJob(job)
> jobQueue.push(job.id, myParameters)
> ```
> 
> or
> 
> You can break it down into its constituent parts.
> 
> ```swift
> extension JobIdentifier where Parameters == Int {
>     static var test: Self { .init("test") }
> }
> jobQueue.registerJob(id: .test) { _, _ in
>     // do job
> }
> jobQueue.push(.test, 5)
> ```
> 
> This along with the `JobDefinition` allow you to use any type as parameters but these methods also have their own issues as well. The `JobDefinition` requires you to store the id as a variable somewhere. Splitting up the Job definition into parameters, id, and closure means it spread across multiple places in your code which could get messy.

I the problem now. Thanks Adam for the clear explanation. Would it still be an issue where if the push func take the parameter type instead of a string? ex: 


```swift
queue.registerJob(
            parameters: AnotherParameters.self,
            maxRetryCount: 4)
        { (parameters: AnotherParameters, _) in
           /// Perform job
        }
```

```swift 
  someJob.push(AnotherParameters.self, .init(....))
```

**Comment by adam-fowler** [comment]
When you push a job, you need to know the job id and the parameters you are passing to the job. You can currently call
```swift
jobQueue.push(parameters: MyJobParameters(...))
```
 because the JobParameters type includes the job identifier. If `JobParameters` doesn't have the job name then `push` wouldn't know which job you are starting.

I haven't used the parameters type as the identifier for job because currently you can have multiple jobs using the same type (as long as you aren't using JobParameters). JobParameters was introduced later and designed to encapsulate all the data associated with a job.

**Comment by thoven87** [comment]
> When you push a job, you need to know the job id and the parameters you are passing to the job. You can currently call
> 
> ```swift
> jobQueue.push(parameters: MyJobParameters(...))
> ```
> 
> because the JobParameters type includes the job identifier. If `JobParameters` doesn't have the job name then `push` wouldn't know which job you are starting.
> 
> I haven't used the parameters type as the identifier for job because currently you can have multiple jobs using the same type (as long as you aren't using JobParameters). JobParameters was introduced later and designed to encapsulate all the data associated with a job.

Understood, then this issue can be closed. Thanks Adam!
