### ISSUE TITLE
[Question] About JobScheduler Minute partitions

### ISSUE THREAD

**Issue by thoven87** [hummingbird-project/swift-jobs#20]
Am I reading the document and code incorrectly? 

Say, I want to run a job every 15 minutes

```swift
let jobSchedule = JobSchedule([
	.init(job: SomeJobParameters(), schedule: .everyMinute(second: 900))
])
```

This does not seem to work. 

I looked at the tests for [every minute function](https://github.com/hummingbird-project/swift-jobs/blob/main/Tests/JobsTests/JobSchedulerTests.swift#L36)

Should the expected end time changes from 

```swift
try self.testSchedule(start: "2021-06-21T21:10:15Z", expectedEnd: "2021-06-21T21:10:43Z", schedule: .everyMinute(second: 43))
```
to 
```swift
try self.testSchedule(start: "2021-06-21T21:10:15Z", expectedEnd: "2021-06-21T21:10:58Z", schedule: .everyMinute(second: 43))
```

**Comment by adam-fowler** [comment]
I haven't got support yet for fractions of a minute, hour etc
Not totally sure how I'd do it with the `Calendar.nextDate` API

**Comment by thoven87** [comment]
> I haven't got support yet for fractions of a minute, hour etc
> 
> Not totally sure how I'd do it with the `Calendar.nextDate` API

Understood, thanks for confirming. I will check to see what I can do.

**Comment by adam-fowler** [comment]
#24 should resolve this
