### ISSUE TITLE
JobScheduler Improvements

### ISSUE THREAD

**Issue by thoven87** [hummingbird-project/swift-jobs#30]
1 - Investigate using [JobQueue push](https://github.com/hummingbird-project/swift-jobs/blob/main/Sources/Jobs/JobQueue.swift#L45) to push jobs onto a queue

2 - I think the Metadata needs updated to use JobName -> last run (or scheduled) instead of `_jobScheduleLastDate` It's a little confusing right now if one has more than one scheduled job

Ex: StatsJob runs every 5 minutes
KPI runs everyday @12 AM UTC

**Comment by adam-fowler** [comment]
> 1 - Investigate using [JobQueue push](https://github.com/hummingbird-project/swift-jobs/blob/main/Sources/Jobs/JobQueue.swift#L45) to push jobs onto a queue
> 
> 
> 
> 2 - I think the Metadata needs updated to use JobName -> last run (or scheduled) instead of `_jobScheduleLastDate` It's a little confusing right now if one has more than one scheduled job
> 
> 
> 
> Ex: StatsJob runs every 5 minutes
> 
> KPI runs everyday @12 AM UTC

Is 1 the same issue as you mentioned earlier?

2 we should only need one last scheduled date for all jobs. It is basically the date we last scheduled something. And at init every schedule should base itself off that. It could be renamed to `lastDateJobScheduled` which makes slightly more sense.

**Comment by adam-fowler** [comment]
> Is 1 the same issue as you mentioned earlier?

I see it is not. It still eventually goes through `JobQueue.push`, but it needs to go through the extension of JobParameters as it needs a concrete `JobParameters` instead of the existential reference we have in the element returned by `JobSequence`

**Comment by thoven87** [comment]
> > 1 - Investigate using [JobQueue push](https://github.com/hummingbird-project/swift-jobs/blob/main/Sources/Jobs/JobQueue.swift#L45) to push jobs onto a queue
> > 2 - I think the Metadata needs updated to use JobName -> last run (or scheduled) instead of `_jobScheduleLastDate` It's a little confusing right now if one has more than one scheduled job
> > Ex: StatsJob runs every 5 minutes
> > KPI runs everyday @12 AM UTC
> 
> Is 1 the same issue as you mentioned earlier?
Yes, it is the same issue mentioned in the [comment here](https://github.com/hummingbird-project/swift-jobs/pull/28#discussion_r1761029083)
> 
> 2 we should only need one last scheduled date for all jobs. It is basically the date we last scheduled something. And at init every schedule should base itself off that. It could be renamed to `lastDateJobScheduled` which makes slightly more sense.

I see! The scheduled job itself can manage the last time it ran and generate a revision id.

**Comment by thoven87** [comment]
> > Is 1 the same issue as you mentioned earlier?
> 
> I see it is not. It still eventually goes through `JobQueue.push`, but it needs to go through the extension of JobParameters as it needs a concrete `JobParameters` instead of the existential reference we have in the element returned by `JobSequence`

You're correct, I will continue debugging.
