### ISSUE TITLE
JobSchedule not working with .onMinutes(minutes)

### ISSUE THREAD

**Issue by MartinLau7** [hummingbird-project/swift-jobs#37]
I’m not sure if I fully understand how to use JobSchedule. I created a [Demo](https://github.com/MartinLau7/SwiftJobsDemo) where I implemented two scheduled jobs: MailScheduledJob1 (scheduled every 2 minutes) and MailScheduledJob2 (scheduled every 1 minute). However, only MailScheduledJob2 works as expected, while MailScheduledJob1 does not run at all.

If I am using it incorrectly, could you let me know the correct way to set this up? Thank you!

**Comment by adam-fowler** [comment]
Found what it was. Should be fixed by #38

**Comment by adam-fowler** [comment]
Released
