### ISSUE TITLE
Job Scheduling questions

### ISSUE THREAD

**Issue by thoven87** [hummingbird-project/swift-jobs#42]
I have been debugging the schedule job "onMinute" features and it's possible that jobs can fall behind and never run again.

For example here, I ran a job on `2024-11-02` @ 14:40, the job is scheduled to run every 5 minutes. Today is 2024-11-29, after kicking off the jobs performance test again, I see the followings in the logs

```sh
2024-11-29T02:11:05-0500 debug io.stevenson.server : [Jobs] Last scheduled date 2024-11-02 14:40:00 +0000.
2024-11-29T02:11:05-0500 debug io.stevenson.server : [Jobs] Last scheduled date 2024-11-02 14:40:00 +0000.
2024-11-29T02:11:05-0500 debug io.stevenson.server : JobName=StatsJob JobTime=2024-11-02 14:45:00 +0000 [Jobs] Next Scheduled Job
```

After trying to troubleshoot this issue for a while, I am at a loss [here](https://github.com/hummingbird-project/swift-jobs/blob/main/Sources/Jobs/Scheduler/JobSchedule.swift#L62) [this is supposed](https://developer.apple.com/documentation/foundation/date/1779684-distantfuture) to return a date in the future where future is not yet known?

Is it advisable to have one job controller per schedule one is one controller is enough. I know if there's at least an everyMinute or everyHour schedule, the next onMinute schedule gets run.

**Comment by adam-fowler** [comment]
Are you saying that scheduled job (in the logs) never runs?

You are better with one JobController. Set its number of workers to the number of cores on the system, although you could experiment with running with more workers and see if their work can interleave. If you aren't processing enough jobs in time then add another machine.

**Comment by thoven87** [comment]
I don't think the issue is the number of cores as the laptop has `10-core` and the job is supposed to use at least 4 of them. I put log statements in the "StatsJob" which confirms it never run. If I delete the current entry for `_jobScheduleLastDate` in the database, the job will run as expected.

**Comment by adam-fowler** [comment]
Why did you close this?

**Comment by thoven87** [comment]
> Why did you close this? 

I apologize, I am just now seeing this message. I closed it because I couldn't reproduce the issue after removing the last scheduled entry from the Postgres database. I lost the work I was doing on the job due to what I described in the discord channel. I am starting a new repo to gather this work and will share.
